version: '3.9'

services:
  backend:
    build:
      context: .
      dockerfile: TaskManager.Server/Dockerfile
    ports:
      - "5000:80"
      - "5213:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    depends_on:
      - db
    networks:
      - app-network

  frontend:
    build:
      context: ./taskmanager.client
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    networks:
      - app-network

  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "123qwe"
      ACCEPT_EULA: "Y"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
